name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files
        run: |
          # 1. Créer le dossier s'il n'existe pas
          sudo mkdir -p /var/www/portefolio
          
          # 2. Synchroniser les fichiers avec sudo
          # On utilise --delete pour supprimer les fichiers qui n'existent plus sur GitHub
          sudo rsync -av --delete --exclude='.git*' --exclude='config/config.php' ./ /var/www/portefolio/

      - name: Set permissions
        run: |
          # 3. Ajuster les droits pour que Nginx puisse lire le site
          sudo chmod -R 755 /var/www/portefolio/
          sudo chown -R www-data:www-data /var/www/portefolio/

      - name: Reload Nginx
        run: |
          # 4. Recharger Nginx pour appliquer les changements si nécessaire
          sudo systemctl reload nginx

# Note:test deplaydeploy